# Generated by Django 6.0.2 on 2026-03-13 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('groups', '0002_initial'),
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plangrupal',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plangrupal',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plangrupal',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plangrupal',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes_liderados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plangrupal',
            name='nombre',
            field=models.CharField(default='Plan', max_length=255),
        ),
        migrations.AddField(
            model_name='plangrupal',
            name='tipo_plan',
            field=models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal')], default='grupal', max_length=20),
        ),
        migrations.AlterField(
            model_name='plangrupal',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('propuesto', 'Propuesto'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='propuesto', max_length=20),
        ),
        migrations.AlterField(
            model_name='plangrupal',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='groups.grupo'),
        ),
        migrations.AlterField(
            model_name='plangrupal',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicio'),
        ),
        migrations.CreateModel(
            name='ActividadPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='groups.plangrupal')),
            ],
            options={
                'ordering': ['fecha_inicio', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ActividadServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('interes', 'Interés'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='interes', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_asignados', to='groups.actividadplan')),
                ('movimiento_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.movimientofinanciero')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicio')),
                ('usuario_asignador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCambioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambios', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio', to='groups.plangrupal')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotoCambioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(null=True)),
                ('fecha_voto', models.DateTimeField(blank=True, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='groups.solicitudcambioplan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('solicitud', 'usuario')},
            },
        ),
    ]
