# Generated by Django 6.0.2 on 2026-03-22 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_plangrupal_descripcion_plangrupal_fecha_fin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente_confirmacion', 'Pendiente confirmación'), ('interes', 'Interés'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='interes', max_length=30),
        ),
        migrations.CreateModel(
            name='ConfirmacionServicioIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('mensaje', models.TextField(default='Se requiere tu confirmación para agregar este servicio a una actividad.')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='groups.actividadservicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('asignacion', 'usuario')},
            },
        ),
    ]
