# Generated by Django 6.0.2 on 2026-02-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('ruc', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('contacto_referencia', models.CharField(max_length=255)),
                ('aprobado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('capacidad_maxima', models.PositiveIntegerField()),
                ('costo_regular', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiene_promocion', models.BooleanField(default=False)),
                ('costo_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lugar', models.CharField(max_length=255)),
                ('contacto_referencia', models.CharField(max_length=255)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
