# Generated by Django 6.0.2 on 2026-03-27 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_entidad_imagenes_promocionales_servicio_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ServicioHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='services.servicio')),
            ],
            options={
                'ordering': ['fecha_inicio', 'fecha_fin', 'id'],
            },
        ),
    ]
