# Generated by Django 6.0.2 on 2026-03-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicio_hora_fin_alter_servicio_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descripcion_forma_pago',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='dias_antes_pago_previo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='modalidad_pago',
            field=models.CharField(choices=[('reserva', 'Reserva'), ('pago_completo', 'Pago completo'), ('contraentrega', 'Contraentrega'), ('reserva_previo_saldo', 'Reserva, pago previo y saldo final'), ('reserva_total_previo', 'Reserva y pago total antes del servicio'), ('otra', 'Otra')], default='pago_completo', max_length=40),
        ),
        migrations.AddField(
            model_name='servicio',
            name='porcentaje_pago_previo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='porcentaje_reserva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
