# Generated by Django 6.0.2 on 2026-04-25 22:45

from django.db import migrations, models
from django.utils.text import slugify


def seed_service_categories(apps, schema_editor):
    Servicio = apps.get_model("services", "Servicio")
    ServicioCategoria = apps.get_model("services", "ServicioCategoria")

    default_categories = [
        "General",
        "Tours",
        "Aventura",
        "Gastronomia",
        "City Tour",
    ]
    existing_categories = list(
        Servicio.objects.exclude(categoria__isnull=True)
        .exclude(categoria__exact="")
        .values_list("categoria", flat=True)
        .distinct()
    )

    ordered_names = []
    for name in [*default_categories, *existing_categories]:
        normalized = (name or "").strip()
        if normalized and normalized not in ordered_names:
            ordered_names.append(normalized)

    for index, name in enumerate(ordered_names):
        base_slug = slugify(name) or f"categoria-{index + 1}"
        slug = base_slug
        suffix = 2
        while ServicioCategoria.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{suffix}"
            suffix += 1
        ServicioCategoria.objects.get_or_create(
            nombre=name,
            defaults={"orden": index, "slug": slug},
        )


def unseed_service_categories(apps, schema_editor):
    ServicioCategoria = apps.get_model("services", "ServicioCategoria")
    ServicioCategoria.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicio_descripcion_forma_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de servicio',
                'verbose_name_plural': 'Categorias de servicio',
                'ordering': ['orden', 'nombre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='total_visualizaciones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(seed_service_categories, unseed_service_categories),
    ]
