# Generated by Django 6.0.2 on 2026-02-15 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='foto',
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.CharField(choices=[('persona', 'Persona'), ('entidad', 'Entidad')], max_length=20),
        ),
        migrations.CreateModel(
            name='PersonaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('cedula', 'Cédula'), ('otro', 'Otro')], max_length=20)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('ocupacion', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
