# Generated by Django 6.0.2 on 2026-04-25 22:45

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaphoto',
            name='imagen',
            field=models.ImageField(upload_to=users.models.persona_photo_upload_to),
        ),
    ]
