# Generated by Django 6.0.2 on 2026-02-15 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionmovimiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.grupo'),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='plan_grupal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.plangrupal'),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='divisionmovimiento',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisiones', to='finance.movimientofinanciero'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='deudor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.grupo'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='prestamista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_otorgados', to=settings.AUTH_USER_MODEL),
        ),
    ]
